apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmms-backend
  namespace: vmms-namespace
  labels:
    app: vmms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmms-backend
  template:
    metadata:
      labels:
        app: vmms-backend
    spec:
      containers:
        - name: vmms-backend
          image: ghcr.io/dave-mash/vmms-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 600m
              memory: 900Mi
          # Uncomment and configure if you have ConfigMaps or Secrets
          # envFrom:
          #   - configMapRef:
          #       name: vmms-backend-config
          #   - secretRef:
          #       name: vmms-backend-secrets
      imagePullSecrets:
        - name: regcred
