apiVersion: v1
kind: Service
metadata:
  name: vmms-backend-service
  namespace: default
spec:
  selector:
    app: vmms-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
  type: ClusterIP

#  kubectl apply -f service.yaml -n vmms-namespace